# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/IIITD/ELD_LABs/ELD_LAB_7_AXI_Protocol_Use_And_FFT/FFT_And_AXI_Stream_Protocol/FFT_And_AXI_Stream_Protocol.srcs/sources_1/ip/FFT_0/FFT_0.xci
# IP: The module: 'FFT_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/ELD_LAB_7_AXI_Protocol_Use_And_FFT/FFT_And_AXI_Stream_Protocol/FFT_And_AXI_Stream_Protocol.srcs/sources_1/ip/FFT_0/FFT_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/ELD_LAB_7_AXI_Protocol_Use_And_FFT/FFT_And_AXI_Stream_Protocol/FFT_And_AXI_Stream_Protocol.srcs/sources_1/ip/FFT_0/FFT_0.xci
# IP: The module: 'FFT_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/ELD_LAB_7_AXI_Protocol_Use_And_FFT/FFT_And_AXI_Stream_Protocol/FFT_And_AXI_Stream_Protocol.srcs/sources_1/ip/FFT_0/FFT_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
