# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/IO_system_ila_0_0.xci
# IP: The module: 'IO_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/bd_6766.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766 || ORIG_REF_NAME==bd_6766} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/bd_6766_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_1/bd_6766_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_g_inst_0 || ORIG_REF_NAME==bd_6766_g_inst_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_2/bd_6766_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_aw_0 || ORIG_REF_NAME==bd_6766_slot_0_aw_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_3/bd_6766_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_w_0 || ORIG_REF_NAME==bd_6766_slot_0_w_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_4/bd_6766_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_b_0 || ORIG_REF_NAME==bd_6766_slot_0_b_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_5/bd_6766_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_ar_0 || ORIG_REF_NAME==bd_6766_slot_0_ar_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_6/bd_6766_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_r_0 || ORIG_REF_NAME==bd_6766_slot_0_r_0} -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/bd_6766_ila_lib_0_ooc.xdc

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/bd_6766_ooc.xdc

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/IO_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IO_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/IO_system_ila_0_0.xci
# IP: The module: 'IO_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/bd_6766.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766 || ORIG_REF_NAME==bd_6766} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/bd_6766_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_1/bd_6766_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_g_inst_0 || ORIG_REF_NAME==bd_6766_g_inst_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_2/bd_6766_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_aw_0 || ORIG_REF_NAME==bd_6766_slot_0_aw_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_3/bd_6766_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_w_0 || ORIG_REF_NAME==bd_6766_slot_0_w_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_4/bd_6766_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_b_0 || ORIG_REF_NAME==bd_6766_slot_0_b_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_5/bd_6766_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_ar_0 || ORIG_REF_NAME==bd_6766_slot_0_ar_0} -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_6/bd_6766_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6766_slot_0_r_0 || ORIG_REF_NAME==bd_6766_slot_0_r_0} -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6766_ila_lib_0 || ORIG_REF_NAME==bd_6766_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/ip/ip_0/bd_6766_ila_lib_0_ooc.xdc

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/bd_0/bd_6766_ooc.xdc

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_system_ila_0_0/IO_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IO_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
