# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/IO/IO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO || ORIG_REF_NAME==IO} -quiet] -quiet

# IP: bd/IO/ip/IO_processing_system7_0_0/IO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_processing_system7_0_0 || ORIG_REF_NAME==IO_processing_system7_0_0} -quiet] -quiet

# IP: bd/IO/ip/IO_axi_bram_ctrl_0_0/IO_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_axi_bram_ctrl_0_0 || ORIG_REF_NAME==IO_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/IO/ip/IO_axi_smc_0/IO_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_axi_smc_0 || ORIG_REF_NAME==IO_axi_smc_0} -quiet] -quiet

# IP: bd/IO/ip/IO_rst_ps7_0_50M_0/IO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_rst_ps7_0_50M_0 || ORIG_REF_NAME==IO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/IO/ip/IO_axi_bram_ctrl_0_bram_0/IO_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==IO_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/IO/ip/IO_system_ila_0_0/IO_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IO_system_ila_0_0 || ORIG_REF_NAME==IO_system_ila_0_0} -quiet] -quiet

# XDC: bd/IO/IO_ooc.xdc
