# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0.xci
# IP: The module: 'endSem_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'endSem_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'endSem_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0.xci
# IP: The module: 'endSem_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'endSem_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIITD/ELD_LABs/LAB_END_SEM_4/END_SEM/END_SEM.srcs/sources_1/bd/endSem/ip/endSem_mdm_1_0/endSem_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'endSem_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
