# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZYNQ_block/ZYNQ_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_block || ORIG_REF_NAME==ZYNQ_block} -quiet] -quiet

# IP: bd/ZYNQ_block/ip/ZYNQ_block_processing_system7_0_0/ZYNQ_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZYNQ_block_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_block_processing_system7_0_0} -quiet] -quiet

# XDC: bd/ZYNQ_block/ZYNQ_block_ooc.xdc
