# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_processing_system7_0_0/IO_processing_system7_0_0.xci
# IP: The module: 'IO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_processing_system7_0_0/IO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'IO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_processing_system7_0_0/IO_processing_system7_0_0.xci
# IP: The module: 'IO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIITD/ELD_LABs/LAB_9_IO_BRAM_ILA/IO_BRAM_ILA/IO_BRAM_ILA.srcs/sources_1/bd/IO/ip/IO_processing_system7_0_0/IO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'IO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
